<?php

namespace Ephp\ImapBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AttachRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttachRepository extends EntityRepository
{
}
